import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";

const albert_sans = Albert_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${albert_sans.className} antialiased`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
